[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  timeout = 26

[dev]
  framework = "#static"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
